version: 2

sources:
  - name: googles_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      
  - name: google_sheet
    schema: google_sheet
    tables:
      - name: ex_1

  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user